name: Test
env:
  VITE_API_BASE_URL: ${{ vars.VITE_API_BASE_URL }}
  VITE_GRAPHQL_URI: ${{ vars.VITE_GRAPHQL_URI }}
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    environment: Development
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/prepare
      - run: pnpm test
