name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    environment: Development
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/prepare
      - run: pnpm test
